name: "\U0001F41B Bug Report"
description: "Report a reproducible bug or regression"
title: "[BUG]"
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: synosis
    attributes:
      label: What happened?
      description: Describe the bug in one line?
      placeholder: Bug
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Step to reproduce?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: section
    attributes:
      label: Section
      description: In what part of the project does the bug exists?
      options:
        - app
        - validator
      default: 0
    validations:
      required: true
  - type: textarea
    id: code
    attributes:
      label: Code
      description: Please copy and paste any relevant code (no need to use backticks)
      render: shell
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Please copy and paste any code or log output
