name: format

on: [push]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up environment
        uses: actions/setup-node@v4
      - name: Install dependencies
        run: npm install
        working-directory: .
      - name: Format
        run: nom run format:check
        working-directory: .
